name: uber_driver_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_database: ^10.3.6

  # toast
  fluttertoast: ^8.2.4 

  # uid generator
  uuid: ^3.0.7 

  # google maps
  google_maps_flutter: ^2.5.0

  # geolocator
  geolocator: ^10.1.0

  # http
  http: ^1.1.0

  # provider
  provider: ^6.1.1

  # flutter polyline points
  flutter_polyline_points: ^2.0.0

  # flutter geofire
  flutter_geofire: ^2.0.3

  # firebase messaging
  firebase_messaging: ^14.7.9

  # assets audio player
  assets_audio_player: ^3.1.1

  intl: ^0.17.0

  smooth_star_rating_nsafe: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - music/music_notification.mp3

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
